### ISSUE TITLE
question about roles / groups in your code

### ISSUE THREAD

**Issue by figuerres** [PracticeEngine/SSRS.Security#1]
looking at the [PEUtilities](https://github.com/PracticeEngine/SSRS.Security/blob/master/src/SSRS2017.OpenIDConnect.Security/PE/PEUtilities.cs)

there are a few details i am not sure of and perhaps you can later add comments in the code to help any future users who want to adpot this code.

`bool ValidatePrincipal(string principal)`

checks the list of "groups" for a match and then calls for isvaliduser.

the getallgroups method calls an api that calls "api/SSRS/GetAllRoles"

so are we dealing with a list of roles that as user can have or a list of groups that a user can be a member of  ?

also should i see  "api/SSRS/GetAllRoles" as getting report server security roles or application  roles if this is roles.

just a little confusing as i do not have the PE system code at hand to look at and use to work out what is meant here...

**Comment by rposener** [comment]
Yep, that's an internal method to our code where we can get the roles for the user, that's secured by our IdentityServer4 implementation.  Basically you will want to replace the entire PEUtilities bit with something that does checks against your application or it's security methods.
